name: Nodejs CI

on:
 - push
 - pull_request

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [14.x]

    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v1
      with:
        node-version: ${{ matrix.node-version }}
    - name: npm install, build
      run: |
        make install
      env: 
        CI: true
    - name: Run linter
      run: |
        make lint
    - name: Test & publish code coverage
      uses: paambaati/codeclimate-action@v2.7.4
      env:
        CC_TEST_REPORTER_ID: ${{ f54538b502d7847b6bf97a648b017be616d4d2cb1bd0c8808a36523eb7c9bb31 }}
      with:
        coverageCommand: make test-coverage
        debug: true
